SELECT
    E.FIRST_NAME,
    E.LAST_NAME,
    E.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    E.JOB_ID,
    J.JOB_TITLE
FROM
    EMPLOYEES   E
    JOIN DEPARTMENTS D
    ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
    JOIN JOBS J
    ON (E.JOB_ID = J.JOB_ID)
ORDER BY
    E.EMPLOYEE_ID;

SELECT
    E.FIRST_NAME,
    E.LAST_NAME,
    DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    JOB_ID,
    J.JOB_TITLE
FROM
    EMPLOYEES   E
    JOIN DEPARTMENTS D
    USING (DEPARTMENT_ID)
    JOIN JOBS J
    USING (JOB_ID)
ORDER BY
    E.EMPLOYEE_ID;

SELECT
    E.FIRST_NAME,
    E.LAST_NAME,
    DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    JOB_ID,
    J.JOB_TITLE
FROM
    EMPLOYEES   E
    NATURAL JOIN DEPARTMENTS D
    NATURAL JOIN JOBS J
ORDER BY
    E.EMPLOYEE_ID;